#!/usr/bin/env bash
# =====================================================================
# cctv-server v1.0.2 — production installer for Ubuntu 22.04 / 24.04 x86_64
#
#   sudo ./scripts/install.sh
#
# Deterministic layout resolution — works from the release ZIP:
#   $RELEASE/scripts/install.sh  ->  bin/, web/, config/, systemd/ next to it
# and from a source checkout (flat dev layout) as a fallback. Never assumes
# a particular current working directory.
#
# Layout installed:
#   /opt/cctv-server/{bin,web,models,migrations,docs,VERSION}  (root:cctv, r-x)
#   /etc/cctv-server/config.toml                           (0640 root:cctv)
#   /etc/cctv-server/secrets.env                           (0600 root:root)
#   /var/lib/cctv-server/{database,recordings,snapshots,events,state}  (cctv:cctv)
#   /var/log/cctv-server/                                  (cctv:cctv)
#
# Bootstrap admin password: generated by the binary on first `init`,
# printed once, written once to /etc/cctv-server/.bootstrap-admin-password
# (0600 root:root), then shredded after it has been shown. It is NEVER
# stored in secrets.env / config.toml / the database / logs.
#
# Idempotent: safe to run repeatedly. Exits non-zero when the service does
# not become ready.
# =====================================================================
set -euo pipefail

APP_VERSION="1.0.2"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RELEASE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
DRY_RUN="${CCTV_DRY_RUN:-0}"
BOOTSTRAP_FILE="/etc/cctv-server/.bootstrap-admin-password"

# ---- helpers --------------------------------------------------------
say() { echo "==> $*"; }
die() { echo "ERROR: $*" >&2; exit 1; }

run() {
  if [[ "$DRY_RUN" == "1" ]]; then echo "     [dry-run] $*"; return 0; fi
  "$@"
}

trap 'echo "ERROR: install failed at line $LINENO — re-run the installer to continue." >&2' ERR

# ---- 0. root / OS / arch checks -------------------------------------
[[ $EUID -eq 0 ]] || die "run as root (sudo ./scripts/install.sh)"

ARCH="$(uname -m)"
[[ "$ARCH" == "x86_64" ]] || die "unsupported architecture: $ARCH (this release targets x86_64)"

if [[ -f /etc/os-release ]]; then
  # shellcheck disable=SC1091
  . /etc/os-release
  OS_ID="${ID:-unknown}"
  OS_VER="${VERSION_ID:-unknown}"
  if [[ "$OS_ID" != "ubuntu" && "$OS_ID" != "debian" ]]; then
    die "unsupported OS: $PRETTY_NAME (this installer targets Ubuntu 22.04/24.04)"
  fi
  case "$OS_VER" in
    22.04|24.04) : ;;
    *) echo "WARNING: tested on Ubuntu 22.04/24.04; you are on $PRETTY_NAME — continuing, but verify manually." >&2 ;;
  esac
else
  die "cannot detect OS (/etc/os-release missing)"
fi

# ---- 1. resolve release layout --------------------------------------
# Preferred (release ZIP): $RELEASE/bin/cctv-server, web/, config/, systemd/
BIN_SRC="" WEB_SRC="" CFG_SRC="" UNIT_SRC="" DOCS_SRC=""
for cand in "$RELEASE_DIR/bin/cctv-server" "$SCRIPT_DIR/cctv-server"; do
  [[ -f "$cand" && -x "$cand" ]] && { BIN_SRC="$cand"; break; }
done
for cand in "$RELEASE_DIR/web/index.html" "$SCRIPT_DIR/index.html"; do
  [[ -f "$cand" ]] && { WEB_SRC="$cand"; break; }
done
for cand in "$RELEASE_DIR/config/config.toml" "$RELEASE_DIR/config/config.example.toml" "$SCRIPT_DIR/config.toml"; do
  [[ -f "$cand" ]] && { CFG_SRC="$cand"; break; }
done
for cand in "$RELEASE_DIR/systemd/cctv-server.service" "$SCRIPT_DIR/cctv-server.service"; do
  [[ -f "$cand" ]] && { UNIT_SRC="$cand"; break; }
done
for cand in "$RELEASE_DIR/docs" "$SCRIPT_DIR/../docs"; do
  [[ -d "$cand" ]] && { DOCS_SRC="$cand"; break; }
done

[[ -n "$BIN_SRC" ]] || die "cctv-server binary not found (looked in $RELEASE_DIR/bin and $SCRIPT_DIR)"
[[ -n "$WEB_SRC" ]] || die "web dashboard not found"
[[ -n "$CFG_SRC" ]] || die "config template not found"
[[ -n "$UNIT_SRC" ]] || die "systemd unit not found"
say "release layout: $(dirname "$BIN_SRC")"

# ---- 2. dependencies -------------------------------------------------
command -v ffmpeg >/dev/null 2>&1 || die "ffmpeg is required (sudo apt install ffmpeg)"
command -v curl >/dev/null 2>&1 || echo "WARNING: curl not found (only needed for remote model install)"

# ---- 3. dedicated system user ---------------------------------------
if ! getent group cctv >/dev/null 2>&1; then
  say "creating group cctv"
  run groupadd --system cctv
fi
if ! getent passwd cctv >/dev/null 2>&1; then
  say "creating system user cctv (no shell, no login)"
  run useradd --system --gid cctv --home-dir /var/lib/cctv-server \
      --shell /usr/sbin/nologin --comment "cctv-server service user" cctv
fi

# ---- 4. directories --------------------------------------------------
say "creating directories"
run install -d -m 0755 -o root -g cctv /opt/cctv-server/bin /opt/cctv-server/web \
                  /opt/cctv-server/models /opt/cctv-server/migrations /opt/cctv-server/docs
run install -d -m 0750 -o root -g cctv /etc/cctv-server
run install -d -m 0750 -o cctv -g cctv /var/lib/cctv-server/database /var/lib/cctv-server/recordings \
                  /var/lib/cctv-server/snapshots /var/lib/cctv-server/events \
                  /var/lib/cctv-server/state
run install -d -m 0750 -o cctv -g cctv /var/log/cctv-server

# ---- 5. binaries & static files --------------------------------------
say "installing binary"
run install -m 0755 -o root -g cctv "$BIN_SRC" /opt/cctv-server/bin/cctv-server
say "installing web dashboard"
run install -m 0644 -o root -g cctv "$WEB_SRC" /opt/cctv-server/web/index.html
if [[ -n "$DOCS_SRC" && -d "$DOCS_SRC" ]]; then
  say "installing documentation"
  run rm -rf /opt/cctv-server/docs
  run cp -a "$DOCS_SRC" /opt/cctv-server/docs
  # also ship the top-level README as the docs index (Documentation= points here)
  if [[ -f "$RELEASE_DIR/README.md" ]]; then
    run install -m 0644 -o root -g cctv "$RELEASE_DIR/README.md" /opt/cctv-server/docs/README.md
  fi
  run chown -R root:cctv /opt/cctv-server/docs
  run find /opt/cctv-server/docs -type f -exec chmod 0644 {} +
  run find /opt/cctv-server/docs -type d -exec chmod 0755 {} +
fi
say "installing VERSION"
printf '%s\n' "$APP_VERSION" | run tee /opt/cctv-server/VERSION >/dev/null

# ---- 6. configuration (idempotent, backup existing) ------------------
say "installing configuration"
if [[ -f /etc/cctv-server/config.toml ]]; then
  cp -a /etc/cctv-server/config.toml "/etc/cctv-server/config.toml.bak.$(date +%Y%m%d%H%M%S)" 2>/dev/null || true
  echo "     existing config kept (backup created)"
else
  run install -m 0640 -o root -g cctv "$CFG_SRC" /etc/cctv-server/config.toml
fi

# ---- 7. secrets file (no secrets currently required) -----------------
say "preparing secrets file"
SECRETS=/etc/cctv-server/secrets.env
if [[ ! -f "$SECRETS" ]]; then
  {
    echo "# cctv-server secrets — generated at install time, mode 0600"
    echo "# No secret is required at runtime: sessions are opaque server-side"
    echo "# tokens and passwords are Argon2id-hashed in the database."
    echo "# (legacy JWT_SECRET entries are ignored for forward compatibility)"
  } | run tee "$SECRETS" >/dev/null
fi
run chmod 0600 "$SECRETS"
run chown root:root "$SECRETS"

# ---- 8. systemd unit --------------------------------------------------
say "installing systemd unit"
run install -m 0644 -o root -g root "$UNIT_SRC" /etc/systemd/system/cctv-server.service
run systemctl daemon-reload

# ---- 9. environment pre-flight ----------------------------------------
say "environment pre-flight (ffmpeg, directories, database)"
PREFLIGHT_OK=0
if [[ "$DRY_RUN" != "1" ]]; then
  if /opt/cctv-server/bin/cctv-server env-guard --config /etc/cctv-server/config.toml; then
    PREFLIGHT_OK=1
  else
    echo "ERROR: environment pre-flight failed — fix the reported issue and re-run." >&2
    exit 1
  fi
else
  PREFLIGHT_OK=1
fi

# ---- 10. database init (first-run random admin password) --------------
say "initializing database (first-run admin password is generated once)"
if [[ "$DRY_RUN" == "1" ]]; then
  run /opt/cctv-server/bin/cctv-server init --config /etc/cctv-server/config.toml --password-file "$BOOTSTRAP_FILE"
else
  rm -f "$BOOTSTRAP_FILE"
  INIT_OUT="$(/opt/cctv-server/bin/cctv-server init --config /etc/cctv-server/config.toml --password-file "$BOOTSTRAP_FILE" 2>&1 || true)"
  echo "$INIT_OUT" | sed 's/^/     /'
  ADMIN_PW=""
  if [[ -f "$BOOTSTRAP_FILE" ]]; then
    ADMIN_PW="$(sed -n 's/^CCTV_ADMIN_PASSWORD=//p' "$BOOTSTRAP_FILE" | head -1)"
  fi
fi

# ---- 11. ownership of mutable data ------------------------------------
say "setting data ownership"
run chown -R cctv:cctv /var/lib/cctv-server
run chown cctv:cctv /var/log/cctv-server

# ---- 12. start + readiness (non-zero on failure) ----------------------
say "enabling and starting service"
run systemctl enable cctv-server
run systemctl start cctv-server || {
  echo "ERROR: service failed to start — check: journalctl -u cctv-server -n 50" >&2
  exit 1
}

say "waiting for readiness (/api/ready)"
OK=0
for i in $(seq 1 45); do
  if curl -fsS --max-time 2 http://127.0.0.1:8080/api/ready >/dev/null 2>&1; then
    OK=1; break
  fi
  if ! systemctl is-active --quiet cctv-server; then
    echo "ERROR: service died while waiting for readiness — check: journalctl -u cctv-server -n 50" >&2
    exit 1
  fi
  sleep 1
done
if [[ "$OK" != "1" ]]; then
  echo "ERROR: service did not become ready within 45s (last logs below):" >&2
  journalctl -u cctv-server -n 20 --no-pager >&2 || true
  exit 1
fi
say "readiness passed"

echo
echo "============================================================"
echo "  cctv-server $APP_VERSION installed successfully."
echo "  dashboard: http://$(hostname -I 2>/dev/null | awk '{print $1}'):8080"
echo "  status:    systemctl status cctv-server"
echo "  logs:      journalctl -u cctv-server -f"
if [[ -n "$ADMIN_PW" ]]; then
  echo
  echo "  >>> FIRST-RUN ADMIN PASSWORD (shown once):"
  echo "  >>>   user: admin"
  echo "  >>>   pass: $ADMIN_PW"
  echo "  >>> CHANGE IT IMMEDIATELY after first login. This password is"
  echo "  >>> not stored anywhere (the temporary bootstrap file was just"
  echo "  >>> deleted). Recovery if lost: docs/OPERATIONS.md, 'Lost admin"
  echo "  >>> password'."
  # delete the temporary bootstrap file (never persists plaintext)
  rm -f "$BOOTSTRAP_FILE" 2>/dev/null || true
else
  echo "  admin password: set by you via config/env (see install docs)."
fi
echo "============================================================"
echo
echo "Models: put yolov8n.onnx into /opt/cctv-server/models/ and restart,"
echo "        or: cctv-server model install <url> && systemctl restart cctv-server"
